DROP TABLE
IF EXISTS `user`;

CREATE TABLE `user` (
	`id` INT (11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
	`username` VARCHAR (20) DEFAULT NULL COMMENT '姓名',
	`nickname` VARCHAR (20) DEFAULT NULL COMMENT '昵称',
	`account` VARCHAR (20) NOT NULL COMMENT '账户',
	`password` VARCHAR (32) NOT NULL COMMENT '密码',
	`phone` VARCHAR (11) DEFAULT NULL COMMENT '手机号',
	`email` VARCHAR (60) DEFAULT NULL COMMENT '邮箱',
	`address` VARCHAR (255) DEFAULT NULL COMMENT '地址',
	`status` INT (1) NOT NULL DEFAULT '1' COMMENT '状态',#0删除，1正常
	`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`modify_time` TIMESTAMP DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
	`last_login_time` TIMESTAMP DEFAULT NULL COMMENT '上次登录时间',
	PRIMARY KEY (`id`)
) ENGINE = INNODB DEFAULT CHARSET = utf8;

DROP TABLE
IF EXISTS `user_token`;

CREATE TABLE `user_token` (
	`user_id` INT (11) UNSIGNED NOT NULL COMMENT '用户ID',
	`token` VARCHAR (40) DEFAULT NULL COMMENT 'token字符串',
	`timeout` INT DEFAULT NULL COMMENT '过期时间',
	`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modify_time` TIMESTAMP DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
) ENGINE = INNODB DEFAULT CHARSET = utf8;

DROP TABLE
IF EXISTS `category`;

CREATE TABLE `category` (
	`id` INT (11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
	`name` VARCHAR (50) NOT NULL COMMENT '分类名称',
	`status` INT (1) NOT NULL DEFAULT '1' COMMENT '状态',#0删除，1正常
	`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`modify_time` TIMESTAMP DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
	PRIMARY KEY (`id`)
) ENGINE = INNODB DEFAULT CHARSET = utf8;

DROP TABLE
IF EXISTS `article`;

CREATE TABLE `article` (
	`id` INT (11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
	`user_id` INT (11) UNSIGNED NOT NULL DEFAULT '0' COMMENT '用户ID',
	`category_id` INT (11) UNSIGNED NOT NULL DEFAULT '0' COMMENT '分类ID',
	`title` VARCHAR (100) NOT NULL COMMENT '文章标题',
	`description` VARCHAR (255) DEFAULT NULL COMMENT '文章简介',
	`content` text NOT NULL COMMENT '文章内容',
	`status` INT (1) NOT NULL DEFAULT '1' COMMENT '状态',#0删除，1正常，2私有
	`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`modify_time` TIMESTAMP DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
	PRIMARY KEY (`id`),
	KEY `userId` (`user_id`),
	KEY `category_id` (`category_id`),
	CONSTRAINT `user_id` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`),
	CONSTRAINT `category_id` FOREIGN KEY (`category_id`) REFERENCES `category` (`id`)
) ENGINE = INNODB DEFAULT CHARSET = utf8;

DROP TABLE
IF EXISTS `comment`;

CREATE TABLE `comment` (
	`id` INT (11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
	`user_id` INT (11) UNSIGNED NOT NULL DEFAULT '0' COMMENT '用户ID',
	`article_id` INT (11) UNSIGNED NOT NULL DEFAULT '0' COMMENT '文章ID',
	`content` text NOT NULL COMMENT '评论内容',
	`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '评论时间',
	`status` INT (1) NOT NULL DEFAULT '1' COMMENT '状态',#0删除，1正常
	`parent_id` INT (1) NOT NULL DEFAULT '0' COMMENT '父ID',#0一级评论
	PRIMARY KEY (`id`),
	KEY `userId` (`user_id`),
	KEY `article_id` (`article_id`),
	CONSTRAINT `user_id` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`),
	CONSTRAINT `article_id` FOREIGN KEY (`article_id`) REFERENCES `article` (`id`)
) ENGINE = INNODB DEFAULT CHARSET = utf8;